#161199259 Create slack channel from create team form
andela/taps-client pull request #37
Opened 2018-10-15 12:29 UTC by phemonick

#### What does this PR do?
- add functionality to create slack channels.

#### Description of Task to be completed?
- add functionality to create multiple slack channels on create team form.

#### How should this be manually tested?
- Login to the review app as an admin
- Click on the create-team icon on the navigation panel
- Fill in valid form credentials and select 1(one) or more slack channel name
- Click on the submit button.

#### Any background context you want to provide?
- N/A

#### What are the relevant pivotal tracker stories?
[#161199259](https://www.pivotaltracker.com/story/show/161199259)

#### Screenshots (if appropriate)
<img width="1143" alt="screen shot 2018-10-15 at 1 11 19 pm" src="https://user-images.githubusercontent.com/23261181/46950823-f386fe80-d07d-11e8-8078-a097e8740ba3.png">

#### Questions:

2018-10-15 16:00 UTC, veeqtor approved these changes
Good work.

2018-10-16 15:04 UTC, nouwatinjacob approved these changes

2018-10-17 16:47 UTC, Chieze-Franklin requested changes

2018-10-17 16:47 UTC, Chieze-Franklin commented on client/src/redux/actions/teams/index.js
> +      pt: 'pt_private_project',
```suggestion
      pt: 'pt_project',
```

2018-10-17 16:47 UTC, Chieze-Franklin commented on client/src/tests/__mocks__/__mockData__/createTeamMock.js
> +    name: 'ghoulie-general',
Why the hard-coded string `'ghoulie-general'`?

2018-10-17 16:47 UTC, Chieze-Franklin commented on client/src/tests/__mocks__/__mockData__/createTeamMock.js
> +    name: 'ghoulie-general',
Oh. This is test. my bad.

2018-10-17 17:43 UTC, Chieze-Franklin approved these changes

2018-10-17 17:43 UTC, merged